# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/unusual_action.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto/unusual_action.proto\"p\n\x1aInformUnusualActionRequest\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0f\n\x07occurAt\x18\x03 \x01(\t\x12\x0e\n\x06roomId\x18\x04 \x01(\x03\x12\x0e\n\x06userId\x18\x05 \x01(\x03\".\n\x1bInformUnusualActionResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2a\n\rUnusualAction\x12P\n\x13InformUnusualAction\x12\x1b.InformUnusualActionRequest\x1a\x1c.InformUnusualActionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.unusual_action_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_INFORMUNUSUALACTIONREQUEST']._serialized_start=30
  _globals['_INFORMUNUSUALACTIONREQUEST']._serialized_end=142
  _globals['_INFORMUNUSUALACTIONRESPONSE']._serialized_start=144
  _globals['_INFORMUNUSUALACTIONRESPONSE']._serialized_end=190
  _globals['_UNUSUALACTION']._serialized_start=192
  _globals['_UNUSUALACTION']._serialized_end=289
# @@protoc_insertion_point(module_scope)
